### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by silopolis** [unrouted/surge#132]
Hi,

Any doc or blog post somewhere or in sight?
Would love to know more about this project as I hope it will be a nice alternative to Tailscale operator... 🤞 

TY
J

**Comment by Jc2k** [comment]
No, its just a little something I made for myself and haven't had the bandwidth to do much with. 

Here's an example manifest:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: surge
  name: surge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: surge
    app.kubernetes.io/component: operator
  name: operator
  namespace: surge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: surge
    app.kubernetes.io/component: operator
  name: surge:operator
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: surge
    app.kubernetes.io/component: operator
  name: surge:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: surge:operator
subjects:
- kind: ServiceAccount
  name: operator
  namespace: surge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: surge
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: surge
      app.kubernetes.io/component: operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: surge
        app.kubernetes.io/component: operator
    spec:
      containers:
      - image: ghcr.io/unrouted/surge:1.0.7
        imagePullPolicy: IfNotPresent
        name: operator
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
        env:
        - name: SURGE_CONTROL_PLANE_URL
          value: https://xxx.xxx.xxx.uk:443
        - name: SURGE_CONTROL_PLANE_AUTH
          value: xxxxxx
        - name: SURGE_DEFAULT_USER
          value: bob
        - name: SURGE_STORAGE_CLASS
          value: some-longhorn-storage-class
        - name: SURGE_LOAD_BALANCER_CLASS
          value: headscale
        - name: SURGE_TAILSCALE_IMAGE
          value: ghcr.io/tailscale/tailscale:v1.78.1
      serviceAccountName: operator
```

Fill in the env variables.

Then add a service like this:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    surge.unrouted.uk/hostname: somehostname
  name: tailscale
  namespace: somenamespace
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  loadBalancerClass: headscale
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: xxxx
    component: app
  type: LoadBalancer
```

It looks for loadBalancerClass that matches the env vars. It will spin up a deployment with a pv from the storage class you gave it in the env (i use longhorn). The deployment will be paired against the control plane in the env var. The machine/node name is picked up from the label on the service. IP from headscale will get added to the kubernetes status field so shows up in kube get svc.

Thats about all it does.

It currently WFM, YMMV.
